name: 签到

on:
  workflow_dispatch:
  schedule:
    - cron: 20 18 * * ?
    
jobs:
  run-it:
    runs-on: ubuntu-18.04
    name: 签到
    steps:
        - name: Checkout codes
          uses: actions/checkout@v2
          
        - name: 运行时间
          run: |
           time=$(curl -s "http://quan.suning.com/getSysTime.do")
           echo -e "当前时间：$(echo "${time}" | awk -F '":"|","' '{print $2}')"
 
        - name: 运行号码签到
          env:
           PARAMETER: ${{ secrets.PARAMETER }}
          run: |
           bash CnUnicom.sh $PARAMETER
