name: 签到

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: 10 06,20 * * ?
    
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 签到
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
        - name: Checkout codes
          uses: actions/checkout@v2
          
        - name: 运行时间
          run: |
           time=$(curl "http://quan.suning.com/getSysTime.do")
           echo -e ${time}
 
        - name: Run 号码1
          env:
           haoma: ${{ secrets.HAOMA }}
           mm: ${{ secrets.MM }}
           appid: ${{ secrets.APPID }}
          run: |
           bash CnUnicom.sh
